feat: portless endpoints
msqd/harp pull request #583
Opened 2024-11-01 10:17 UTC by ArthurD1

2024-11-01 10:21 UTC, ArthurD1 commented on harp/controllers/resolvers.py
> +    _name_to_controller: dict[str, IAsyncController]
Suggestions for this variable name are welcome

2024-11-01 11:33 UTC, Lenormju commented on harp/controllers/resolvers.py
> +    _name_to_controller: dict[str, IAsyncController]
looks good to me

2024-11-01 11:36 UTC, hartym requested changes
Small update to documentation somewhere ?

2024-11-01 11:36 UTC, hartym commented on docs/changelogs/unreleased.rst
> +Changed
```suggestion
Added
```

2024-11-06 08:59 UTC, hartym requested changes
### Missing

- Backend tests: even if this is not a huge amount of code, it is structuring and depending on the fact that it exists needs to be reliable.
- Documentation: there should be a reference somewhere in the documentation about the fact that this is possible, and how to configure it. It does not need to be a lot, but a few pages should be reviewed and at least have a small reference to it.

### Doc candidates

- https://docs.harp-proxy.net/en/latest/features/proxy.html
- https://docs.harp-proxy.net/en/latest/apps/proxy/index.html
- https://docs.harp-proxy.net/en/latest/apps/proxy/settings.html

2024-11-07 08:12 UTC, hartym requested changes

2024-11-07 08:12 UTC, hartym commented on docs/features/proxy.rst
> +A port is not required to configure an endpoint for the proxy. This is for advanced use cases only such as defining a specific behaviour of the proxy for a specific endpoint.
```suggestion
A port is not required to configure an endpoint for the proxy. This is for advanced use cases only such as using an endpoint from within another controller (internal subrequests).
```

2024-11-07 08:12 UTC, hartym commented on docs/features/proxy.rst
> +A port is not required to configure an endpoint for the proxy. This is for advanced use cases only such as defining a specific behaviour of the proxy for a specific endpoint.
Not certain about my suggestion but «defining a specific behaviour of the proxy for a specific endpoint» does not bring much information, and does not sound very specific.

2024-11-07 08:12 UTC, hartym commented on harp/controllers/tests/test_resolvers.py
> +    assert isinstance(resolver._name_to_controller["test-endpoint"], HttpProxyController)
Can we avoid the internal implementation detail in test ? I'd like to avoid tying the test to the specific internal attribute, I think that testing the outside behaviour is enough.

2024-11-07 09:19 UTC, hartym approved these changes

2024-11-07 09:19 UTC, merged