Issue #542: Fix cli user command --set x=y or --set x y
msqd/harp pull request #590
Opened 2024-11-01 16:12 UTC by masterivanic

2024-11-03 15:01 UTC, ArthurD1 requested changes
Looks good to me overall 👍 but I believe we could add a test and remove the reformatted file from the PR.

2024-11-03 15:01 UTC, ArthurD1 commented on .github/workflows/documentation.yml
This file has been formatted but should not be part of that PR.

2024-11-03 15:01 UTC, ArthurD1 commented on harp_apps/dashboard/frontend/package.json
> +  "packageManager": "pnpm@9.12.3+sha512.cce0f9de9c5a7c95bef944169cc5dfe8741abfb145078c0d508b868056848a87c81e626246cb60967cbd7fd29a6c062ef73ff840d96b3c86c40ac92cf4a813ee"
I think we can remove this:

```suggestion
```

2024-11-03 15:01 UTC, ArthurD1 commented on harp/commandline/server.py
> +    def parse_args(self, ctx: click.Context, args: List[str]) -> List[str]:
Looks good to me 👍 , can we add a test for this?

2024-11-03 15:04 UTC, masterivanic commented on harp/commandline/server.py
> +    def parse_args(self, ctx: click.Context, args: List[str]) -> List[str]:
Here, i think. I may check to add a unit for

2024-11-03 15:06 UTC, masterivanic commented on .github/workflows/documentation.yml
pre-commit reformated after doing --all-files

2024-11-03 17:31 UTC, Lenormju reviewed
I have followed [conventional comments](https://conventionalcomments.org/) for this review.
It works as-is, bu I have a question, and some suggestions to do.

2024-11-03 17:31 UTC, Lenormju commented on .github/workflows/documentation.yml
**nitpick**: Lots of whitespace removals in this file. I don't know what is expected for Harp regarding this.

2024-11-03 17:31 UTC, Lenormju commented on harp_apps/dashboard/frontend/package.json
**question(blocking)**: I don't know if the `pnpm` version should be pinned or not.

2024-11-03 17:31 UTC, Lenormju commented on harp/commandline/options/server.py
> +    options: Union[dict, tuple] = field(default_factory=dict)
**question(blocking)**: is it actually required ?

2024-11-03 17:31 UTC, Lenormju commented on harp/commandline/options/server.py
> +            help=f"Add configuration options (e.g. {code('--set foo=bar')} or {code('--set foo bar')}, can be used multiple times).",
**praise**: nice to have added it to the docs 😃

2024-11-03 17:31 UTC, Lenormju commented on harp/commandline/server.py
> +    def parse_args(self, ctx: click.Context, args: List[str]) -> List[str]:
I have worked on some `doctest` (with a slight refactor to avoid having to pass `ctx` and `self` while testing) :
```python
class FixArgvOptionSetValues(click.Command):
    """
    Overrides the standard `click.Command.parse_args` method
    to support auto-fixing args used by the `--set` option.

    >>> FixArgvOptionSetValues._fix_option_set_values(["--set", "a", "3", "--set", "b=4"])
    ['--set', 'a=3', '--set', 'b=4']
    """

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)

    def parse_args(self, ctx: click.Context, args: List[str]) -> List[str]:
        return super().parse_args(ctx, self._fix_option_set_values(args))

    @staticmethod
    def _fix_option_set_values(args: List[str]) -> List[str]:
        index: int = 0
        while index < len(args):
            if args[index] == "--set":
                if index + 2 < len(args):
                    if not (args[index + 1].startswith("-") or args[index + 2].startswith("-")):
                        args[index + 1] += "=" + args[index + 2]
                        del args[index + 2]

            index += 1
        return args
```
But you may prefer a regular unit test. But I think having an executable example is even better in the class' docstring.

(I had a few problems regarding the `harp.commandline.config` module which was causing some conflict with the `config-essentials` library that is also imported as `config`. I talked with @ArthurD1 about that, but it seems it is only a problem for doctest (which does some `importlib` magic))

2024-11-06 09:12 UTC, hartym commented on harp_apps/dashboard/frontend/package.json
removed.

2024-11-06 09:41 UTC, hartym commented on .github/workflows/documentation.yml
This is an outdated file that is not used anymore. Pre commit should not have picked it up, but I'll resolve the topic by removing the file.

2024-11-06 09:48 UTC, hartym commented on harp/commandline/server.py
> +    def parse_args(self, ctx: click.Context, args: List[str]) -> List[str]:
Yes, package name choice for config-essentials is imho not ideal at best.

Having a test there is indeed important, I don't really care if it's a doctest, a unit test or somethingelse test, as long as it runs with `make qa`. As I understand the PR, this is implemented on the `harp server` command and not `harp start`, which is a good first step but makes it even more important to test it as it will need to be used in other commands too (in fact, there are a bunch of commands that supports `--set` and they should all behave the same). I'm not familiar enough with `click` to know what's the best practice there.

2024-11-06 09:49 UTC, hartym commented on .github/workflows/documentation.yml
File removed, problem solved.

2024-11-06 13:50 UTC, masterivanic commented on harp/commandline/server.py
> +    def parse_args(self, ctx: click.Context, args: List[str]) -> List[str]:
ok i'll check more what click suggest for simplify cli command, i think it will be good to do same with harp server command. Maybe it already done

2024-11-06 13:51 UTC, masterivanic commented on harp/commandline/options/server.py
> +    options: Union[dict, tuple] = field(default_factory=dict)
@Lenormju  no, u can remove by the way if you want

2024-11-09 16:42 UTC, hartym commented on harp/commandline/server.py
> +    def parse_args(self, ctx: click.Context, args: List[str]) -> List[str]:
We need both a test and address the fact that we're changing the iterator length while iterating over it. Also, this could be refactored to be paplied to all server commands, not only "harp server" (for example, harp start, or ...)

2024-11-09 18:37 UTC, hartym commented on harp/commandline/server.py
> +    def parse_args(self, ctx: click.Context, args: List[str]) -> List[str]:
I'll refactor this and add tests.

2024-11-09 19:15 UTC, hartym commented
Tests added, takes all commands into account, add the proven ability to use things like `harp <cmd> foo bar --set a=b baz --set c d --something-different`, avoid using unsafe deletes while iterating.

2024-11-10 15:29 UTC, masterivanic reviewed
@hartym  can you create issue or it not need to apply to all cli command same format harp

2024-11-11 07:35 UTC, hartym commented
@masterivanic I did implement it, see 0148f5acb181089d8202fe9050c3cc9d6e07e336

2024-11-11 07:36 UTC, merged