Handle rule defaults in match_level
msqd/harp pull request #592
Opened 2024-11-01 16:20 UTC by Synss

Issue 562

2024-11-03 15:27 UTC, ArthurD1 submitted a review, later dismissed
This seems to break when harp is run with `--enable rules` and no rules are configured.

2024-11-03 15:39 UTC, ArthurD1 requested changes
> This seems to break when harp is run with `--enable rules` and no rules are configured.

It breaks with `TypeError: 'NoneType' object is not iterable`

2024-11-05 21:45 UTC, Synss commented
I’ll have a look.

2024-11-09 18:04 UTC, Synss commented
I've just added a follow-up commit that fixes this issue by adding a simple guard clause upon entering the function. The rules matching will now be skipped entirely when no rules are configured.

I've tried the patch with
```
python -m harp server --enable rules
```
from the repo.

2024-11-10 08:15 UTC, hartym requested changes
We're on a good path, but not quite there yet.

I pushed some fixes related to comments I made, especially the fact that the changes to match item was now skipping matches from different subtrees (because it now used return instead of yield from.

I also added some tests for the potential issue we discussed at pycon, and I have a good and a bad news: the bug discussed does not and did not exist: the `harp_apps.rules.models.rulesets.BaseRuleSet.match` method "flattens" the rules, level by level, and all subtrees are considered. The bad news is, the new __default__ behaviour is having hard time there, because it means that if we have two subtrees with default rules, having a nondefault rule match in the first subtree will make the second subtree default not matching, which is not what I believe we want.

For example: 

```yaml
a:
  foo: ...
b:
  __default__: ...
```
  
If "the "foo" rule match, then default will never be considered.

I added a failing test for this, and I guess we need to address that before we can merge. Another thing needed before it can be merged is some bits of documentation: one should be able to find references to __default__ in the docs, even if it's only a few sentences + examples here and there (no need to overdo it). An entry should also be added to the `docs/changelogs/unreleased.rst` file.

2024-11-10 08:15 UTC, hartym commented on harp_apps/rules/models/rulesets.py
> +        return Itemize(default)
As far as I understand, this changes the behaviour of rules, allowing only one match to be made amongst one level (by returning instead of yielding from). The «itemize» object brings more confusion than clarity, on top of that.

the current test suite is a bit incomplete on the rules side, but catches an issue there (see `harp_apps.rules.tests.test_models_rulesets.test_multilevel`).

2024-11-10 08:15 UTC, hartym commented on harp_apps/rules/models/rulesets.py
> +            return
Is that related to the current patch or a preexisting bug ? Asking because I want to make sure I understand what have caused the change in behaviour if it worked previously. 

Anyway, can't do real harm to check, but probably the empty rules should be iterable anyway (empty iterator). More a note for myself here than anything else.

2024-11-10 09:54 UTC, Synss commented on harp_apps/rules/models/rulesets.py
> +            return
This guards against the ```TypeError: 'NoneType' object is not iterable``` when no rule is configured. This was reported [above](https://github.com/msqd/harp/pull/592#pullrequestreview-2411881338).

2024-11-10 09:58 UTC, Synss commented
Thank you for the detailed feedback! This is really appreciated.

The feature indeed seems more involved than I first thought. I'm still interested in working on this but I must let you know that I'm really busy this month. I apologize if this causes any inconvenience.

2024-11-16 10:09 UTC, hartym commented
@all-contributors add

2024-11-16 10:34 UTC, hartym commented
> The feature indeed seems more involved than I first thought. I'm still interested in working on this but I must let you know that I'm really busy this month. I apologize if this causes any inconvenience.

No worries, take your time, your help is also really appreciated.

2026-06-07 12:53 UTC, closed without merging