Custom type controllers
msqd/harp pull request #609
Opened 2024-11-06 14:05 UTC by ArthurD1

2024-11-06 15:01 UTC, hartym requested changes
Suggested missing test cases:
- what happens if I pass same additional arguments twice to a singleton service?
- what happens if I get the same service twice, with different arguments ? With different lifestyles?
- what happens to arguments if we create scoped services?
- what happens to services that depend on something that we .get() with arguments if we get() it before or after we got the dependency?
- ...

Overall, I'm a bit concerned about the specifics of reimplementation of rodi parts, disconnecting ourselves from the eventual upstream patches. We may need to open an RFC about the future of service management in harp, if we actually need to reimplement most of what rodi does and ignore some other parts of it, we may benefit from rethinking a minimal container that actually suit our needs from inception.

2024-11-06 15:01 UTC, hartym commented on docs/apps/proxy/examples/reference.yml
>      description: null
**question**: is the new expected syntax compatible with the old one? Especially, can we still pass ``null`` to get the default, and can we pass a string too (I guess not, but wouldn't that be ideal, not only for BC but also because a short syntax when applicable may be desirable) ?

2024-11-06 15:01 UTC, hartym commented on docs/reference/core/harp.services.services.rst
> +harp.services.services
**nitpick**: not a big fan of ``xxx.services.services``

2024-11-06 15:01 UTC, hartym commented on harp/config/configurables/service.py
> +        """Convert the service settings to a service definition."""
**thought**: looks like we're building service definitions from configuration for all prior usage, and here we're doing the opposite. Not sure about which one is right but doing it one way or another depending on the use case looks confusing? We may need to have a chat about this.

2024-11-06 15:01 UTC, hartym commented on harp/controllers/resolvers.py
>      ):
**praise**: the interface looks much cleaner, this is an hint that we're toward a good choice.

2024-11-06 15:01 UTC, hartym commented on harp/controllers/resolvers.py
> +        logger.info(f"🏭 Map: *:{port} -> {controller}")
**question**: what happens for a port-less controller?

2024-11-06 15:01 UTC, hartym commented on harp/services/containers.py
> +        with ResolutionContext() as context:
**issue**: this looks like either a copypaste or reimplementation of the parent, without any call to ``super()``. This may be dangerous for future maintenance, if we absolutely **need** to do so, let's document the fact that we're not happy about it, with an explanation on why this choice was made.

2024-11-06 15:01 UTC, hartym commented on harp/services/services.py
> +            raise CannotResolveTypeException(desired_type)
**question**: does that mean that in the case of scoped services we ignore the arguments? What happens if we have a singleton service resolver and we call twice the getter with different arguments ? This change of interface looks very dangerous, because as far as I understand it relies on the user knowing the exact state of the service collection to be able to use it without mistake. I may miss things but it looks a bit more like a hack ?

2024-11-06 15:01 UTC, hartym commented on harp_apps/dashboard/frontend/types/harp_apps.proxy.d.ts
>    }
**issue**: I think we need to support a backward compatible definition? At least it would make sense for the simplest needs?

2024-11-06 15:01 UTC, hartym commented on harp_apps/dashboard/frontend/types/harp_apps.proxy.d.ts
>    export interface Endpoint {
**question**: the ``controller`` part moved to the concrete implementation, is there any reason for this?

2024-11-06 15:01 UTC, hartym commented on harp_apps/proxy/__app__.py
> +                f"{endpoint.name}_controller",
**suggestion**: can we prefix this name with something unique to the application (eg: ``proxy.controllers.*``)? I fear collisions if more than one app have a similar logic?

2024-11-06 15:35 UTC, ArthurD1 commented on docs/apps/proxy/examples/reference.yml
>      description: null
Controller can still be null and the default will be same as before (HttpProxyController).
you can still pass a string as the type of the service.

2024-11-06 15:38 UTC, ArthurD1 commented on harp/config/configurables/service.py
> +        """Convert the service settings to a service definition."""
We are building a service definition from a configurable service here so it sounds like we are still doing what you suggest.

That being said, we could rename Service to be more explicit about which one is a config.

2024-11-06 15:39 UTC, ArthurD1 commented on harp/controllers/resolvers.py
> +        logger.info(f"🏭 Map: *:{port} -> {controller}")
This is not possible here, let's keep that question for another PR.

2024-11-06 16:17 UTC, ArthurD1 commented on harp/services/services.py
> +            raise CannotResolveTypeException(desired_type)
No in the case of scoped services we do not ignore the arguments as the first call to get will create the instance.

In the case of a singleton calling `get` on the provider with different additional arguments will provide the instance that was created on the first call, so arguments will be ignored on the second call.

I agree with the interface not being explicit enough, 2 things actually:

1. Those services cannot be resolved unless we provide missing arguments.
2. They cannot be a dependency of other services because of 1.

2024-11-06 16:17 UTC, ArthurD1 commented on harp_apps/dashboard/frontend/types/harp_apps.proxy.d.ts
>    export interface Endpoint {
Not really no, what is the reason for the concret implementation btw?

2024-11-06 16:18 UTC, ArthurD1 commented on harp_apps/proxy/__app__.py
> +                f"{endpoint.name}_controller",
Sure thing

2024-11-07 07:47 UTC, hartym commented on docs/apps/proxy/examples/reference.yml
>      description: null
As in `controller: foo.bar.Baz` (backward compatible) ?

2024-11-07 07:53 UTC, hartym commented on harp/config/configurables/service.py
> +        """Convert the service settings to a service definition."""
Let's talk about it.

2024-11-07 07:56 UTC, hartym commented on harp/services/services.py
> +            raise CannotResolveTypeException(desired_type)
Ok, it's definitely NOT possible to have an api that will behave differently depending on the calls order. We need to rethink this.

2024-11-07 08:01 UTC, hartym commented on harp_apps/dashboard/frontend/types/harp_apps.proxy.d.ts
>    export interface Endpoint {
Attributes from base are included in the stateful dict-ification while the attributes from the leaf impl are not included in it. It allows to avoid having a tree with many replicas of the same settings when passing it to the frontend for example. In practice, we mostly ignore most collection-based attributes.

Example: RemoteSettings contains `probe` but we dont dump when dumping the Remote's settings, as the children Probe stateful will already have its content.

2024-11-08 10:09 UTC, hartym commented on docs/reference/core/harp.services.services.rst
> +harp.services.services
removed by last changes

2024-11-08 10:10 UTC, hartym commented on harp/services/containers.py
> +        with ResolutionContext() as context:
resolved.

2024-11-08 10:10 UTC, hartym commented on harp/services/services.py
> +            raise CannotResolveTypeException(desired_type)
resolved.

2024-11-08 10:20 UTC, hartym requested changes
Few issues left to fix but we're getting really close to something really nice we can merge! Kudos.

* the unreleased.rst file should be updated
* few cosmetics (see comments)
* there is a question left about backward compatibility and the fact that it was possible to pass a simple string to controller setting, which is now a service definition. Let's see if we can find a way to pass a string to service definition fields (we may be limited by what pydantic allows, but would be neat, even for other config parts where other subfields does not need customization).
* We need to see if the frontend type changes are of any importance, or not.

2024-11-08 10:20 UTC, hartym commented on harp_apps/proxy/__app__.py
> +            event.container._map[name] = resolver
**issue**: the ControllerServiceDefinition can be inlined and if not, the case should be fixed.

2024-11-08 10:20 UTC, hartym commented on harp_apps/proxy/__app__.py
> +            ControllerServiceDefinition = controller.to_service_definition(name, lifestyle="transient")
**issue**: the name formatting is done twice in this file, can be factored into `_get_controller_service_name` (or similar)

2024-11-14 09:04 UTC, merged